export const Agencies = [
  { agency: "Oregon State Police", phone: "8004420776", location: "" },
  {
    agency: "Baker County Sheriff's Office",
    phone: "5415236415",
    location: "",
  },
  {
    agency: "Benton County Sheriff's Office",
    phone: "5417666858",
    location: "",
  },
  {
    agency: "Clackamas County Sheriff's Office ",
    phone: "5036558211",
    location: "",
  },
  {
    agency: "Clatsop County Sheriff's Office",
    phone: "5033252061",
    location: "",
  },
  {
    agency: "Columbia County Sheriff's Office",
    phone: "5033971521",
    location: "",
  },
  { agency: "Coos County Sheriff's Office", phone: "5413967800", location: "" },
  {
    agency: "Crook County Sheriff's Office",
    phone: "5414476398",
    location: "",
  },
  {
    agency: "Curry County Sheriff's Office",
    phone: "5412473242",
    location: "",
  },
  {
    agency: "Deschutes County Sheriff's Office",
    phone: "5416936911",
    location: "",
  },
  {
    agency: "Douglas County Sheriff's Office",
    phone: "5414404471",
    location: "",
  },
  {
    agency: "Gilliam County Sheriff's Office",
    phone: "5413842080",
    location: "",
  },
  {
    agency: "Grant County Sheriff's Office",
    phone: "5415751131",
    location: "",
  },
  {
    agency: "Harney County Sheriff's Office",
    phone: "5415735961",
    location: "",
  },
  {
    agency: "Hood River County Sheriff's Office",
    phone: "5413862711",
    location: "",
  },
  {
    agency: "Jackson County Sheriff's Office",
    phone: "5417746800",
    location: "",
  },
  {
    agency: "Jefferson County Sheriff's Office",
    phone: "5414752201",
    location: "",
  },
  {
    agency: "Josephine County Sheriff's Office",
    phone: "5414745123",
    location: "",
  },
  {
    agency: "Klamath County Sheriff's Office",
    phone: "5418835130",
    location: "",
  },
  {
    agency: "Lake County Sheriff's Office",
    phone: "5419472504 ",
    location: "",
  },
  { agency: "Lane County Sheriff's Office", phone: "5416824150", location: "" },
  {
    agency: "Lincoln County Sheriff's Office",
    phone: "5412650777",
    location: "",
  },
  { agency: "Linn County Sheriff's Office", phone: "5419673950", location: "" },
  {
    agency: "Malheur County Sheriff's Office",
    phone: "5414735126",
    location: "",
  },
  {
    agency: "Marion County Sheriff's Office",
    phone: "5035885032",
    location: "",
  },
  {
    agency: "Morrow County Sheriff's Office",
    phone: "5416765317",
    location: "",
  },
  {
    agency: "Multnomah County Sheriff's Office",
    phone: "5038233333",
    location: "",
  },
  { agency: "Polk County Sheriff's Office", phone: "5036239251", location: "" },
  {
    agency: "Sherman County Sheriff's Office",
    phone: "5415653622",
    location: "",
  },
  {
    agency: "Tillamook County Sheriff's Office",
    phone: "5038151911",
    location: "",
  },
  {
    agency: "Umatilla County Sheriff's Office",
    phone: "5419663651",
    location: "",
  },
  {
    agency: "Union County Sheriff's Office",
    phone: "5419631017",
    location: "",
  },
  {
    agency: "Wallowa County Sheriff's Office",
    phone: "5414263131",
    location: "",
  },
  {
    agency: "Wasco County Sheriff's Office",
    phone: "5415062580",
    location: "",
  },
  {
    agency: "Washington County Sheriff's Office",
    phone: "5036290111",
    location: "",
  },
  {
    agency: "Wheeler County Sheriff's Office",
    phone: "5413842080",
    location: "",
  },
  {
    agency: "Yamhill County Sheriff's Office",
    phone: "5034346500",
    location: "",
  },
  { agency: "Adair Village Police Department", phone: "", location: "" },
  { agency: "Albany Police Department", phone: "", location: "" },
  { agency: "Amity Police Department", phone: "", location: "" },
  { agency: "Ashland Police Department", phone: "", location: "" },
  { agency: "Astoria Police Department", phone: "", location: "" },
  { agency: "Athena Police Department", phone: "", location: "" },
  { agency: "Aumsville Police Department", phone: "", location: "" },
  { agency: "Baker City Police Department", phone: "", location: "" },
  { agency: "Bandon Police Department", phone: "", location: "" },
  { agency: "Beaverton Police Department", phone: "", location: "" },
  { agency: "Bend Police Department", phone: "", location: "" },
  { agency: "Black Butte Ranch Police Department", phone: "", location: "" },
  { agency: "Boardman Police Department", phone: "", location: "" },
  { agency: "Brookings Police Department", phone: "", location: "" },
  { agency: "Burns Police Department", phone: "", location: "" },
  { agency: "Butte Falls Police Department", phone: "", location: "" },
  { agency: "Canby Police Department", phone: "", location: "" },
  { agency: "Cannon Beach Police Department", phone: "", location: "" },
  { agency: "Carlton Police Department", phone: "", location: "" },
  { agency: "Central Point Police Department", phone: "", location: "" },
  { agency: "Clatskanie Police Department", phone: "", location: "" },
  { agency: "Coburg Police Department", phone: "", location: "" },
  { agency: "Columbia City Police Department", phone: "", location: "" },
  { agency: "Condon Police Department", phone: "", location: "" },
  { agency: "Coos Bay Police Department", phone: "", location: "" },
  { agency: "Coquille Police Department", phone: "", location: "" },
  { agency: "Cornelius Police Department", phone: "", location: "" },
  { agency: "Corvallis Police Department", phone: "", location: "" },
  { agency: "Cottage Grove Police Department", phone: "", location: "" },
  { agency: "Dallas Police Department (Oregon)", phone: "", location: "" },
  { agency: "Eagle Point Police Department", phone: "", location: "" },
  { agency: "Enterprise Police Department", phone: "", location: "" },
  { agency: "Eugene Police Department", phone: "", location: "" },
  { agency: "Fairview Police Department", phone: "", location: "" },
  { agency: "Florence Police Department", phone: "", location: "" },
  { agency: "Forest Grove Police Department", phone: "", location: "" },
  { agency: "Gearhart Police Department", phone: "", location: "" },
  { agency: "Gervais Police Department", phone: "", location: "" },
  { agency: "Gladstone Police Department", phone: "", location: "" },
  { agency: "Gold Beach Police Department", phone: "", location: "" },
  {
    agency: "Grants Pass Department of Public Safety",
    phone: "",
    location: "",
  },
  { agency: "Gresham Police Department", phone: "", location: "" },
  { agency: "Hermiston Police Department", phone: "", location: "" },
  { agency: "Hillsboro Police Department", phone: "", location: "" },
  { agency: "Hines Police Department", phone: "", location: "" },
  { agency: "Hood River Police Department", phone: "", location: "" },
  { agency: "Hubbard Police Department", phone: "", location: "" },
  { agency: "Independence Police Department", phone: "", location: "" },
  { agency: "Jacksonville Police Department", phone: "", location: "" },
  { agency: "John Day Police Department", phone: "", location: "" },
  { agency: "Junction City Police Department", phone: "", location: "" },
  { agency: "Keizer Police Department", phone: "", location: "" },
  { agency: "King City Police Department", phone: "", location: "" },
  { agency: "Klamath Falls Police Department", phone: "", location: "" },
  { agency: "La Grande Police Department", phone: "", location: "" },
  { agency: "Lake Oswego Police Department", phone: "", location: "" },
  { agency: "Lakeview Police Department", phone: "", location: "" },
  { agency: "Lebanon Police Department", phone: "", location: "" },
  { agency: "Lincoln City Police Department", phone: "", location: "" },
  { agency: "Madras Police Department", phone: "", location: "" },
  { agency: "Malin Police Department", phone: "", location: "" },
  { agency: "Manzanita Police Department", phone: "", location: "" },
  { agency: "McMinnville Police Department", phone: "", location: "" },
  { agency: "Medford Police Department", phone: "", location: "" },
  { agency: "Merrill Police Department", phone: "", location: "" },
  { agency: "Milton-Freewater Police Department", phone: "", location: "" },
  { agency: "Milwaukie Police Department ", phone: "", location: "" },
  { agency: "Molalla Police Department", phone: "", location: "" },
  { agency: "Monmouth Police Department", phone: "", location: "" },
  { agency: "Mt. Angel Police Department", phone: "", location: "" },
  { agency: "Myrtle Creek Police Department", phone: "", location: "" },
  { agency: "Myrtle Point Police Department", phone: "", location: "" },
  { agency: "Newberg-Dundee Police Department", phone: "", location: "" },
  { agency: "Newport Police Department", phone: "", location: "" },
  { agency: "North Bend Police Department", phone: "", location: "" },
  { agency: "North Plains Police Department", phone: "", location: "" },
  { agency: "Nyssa Police Department", phone: "", location: "" },
  { agency: "Oakland Police Department", phone: "", location: "" },
  { agency: "Oakridge Police Department", phone: "", location: "" },
  { agency: "Ontario Police Department", phone: "", location: "" },
  { agency: "Oregon City Police Department ", phone: "", location: "" },
  { agency: "Pendleton Police Department", phone: "", location: "" },
  { agency: "Philomath Police Department", phone: "", location: "" },
  { agency: "Phoenix Police Department", phone: "", location: "" },
  { agency: "Pilot Rock Police Department", phone: "", location: "" },
  { agency: "Port Orford Police Department", phone: "", location: "" },
  { agency: "Portland Police Bureau", phone: "", location: "" },
  { agency: "Powers Police Department", phone: "", location: "" },
  { agency: "Prairie City Police Department", phone: "", location: "" },
  { agency: "Prineville Police Department", phone: "", location: "" },
  { agency: "Rainier Police Department", phone: "", location: "" },
  { agency: "Redmond Police Department ", phone: "", location: "" },
  { agency: "Reedsport Police Department", phone: "", location: "" },
  { agency: "Rockaway Beach Police Department", phone: "", location: "" },
  { agency: "Rogue River Police Department", phone: "", location: "" },
  { agency: "Roseburg Police Department", phone: "", location: "" },
  { agency: "Salem Police Department", phone: "", location: "" },
  { agency: "Sandy Police Department", phone: "", location: "" },
  { agency: "Scappoose Police Department", phone: "", location: "" },
  { agency: "Seaside Police Department ", phone: "", location: "" },
  { agency: "Sherwood Police Department", phone: "", location: "" },
  { agency: "Silverton Police Department", phone: "", location: "" },
  { agency: "Springfield Police Department", phone: "", location: "" },
  { agency: "St. Helens Police Department", phone: "", location: "" },
  { agency: "Stanfield Police Department", phone: "", location: "" },
  { agency: "Stayton Police Department", phone: "", location: "" },
  { agency: "Sunriver Police Department", phone: "", location: "" },
  { agency: "Sutherlin Police Department", phone: "", location: "" },
  { agency: "Sweet Home Police Department", phone: "", location: "" },
  { agency: "Talent Police Department", phone: "", location: "" },
  { agency: "The Dalles Police Department", phone: "", location: "" },
  { agency: "Tigard Police Department ", phone: "", location: "" },
  { agency: "Tillamook Police Department", phone: "", location: "" },
  { agency: "Toledo Police Department", phone: "", location: "" },
  { agency: "Troutdale Police Department", phone: "", location: "" },
  { agency: "Tualatin Police Department", phone: "", location: "" },
  { agency: "Turner Police Department", phone: "", location: "" },
  { agency: "Umatilla Police Department", phone: "", location: "" },
  { agency: "Vernonia Police Department", phone: "", location: "" },
  { agency: "Warrenton Police Department", phone: "", location: "" },
  { agency: "West Linn Police Department", phone: "", location: "" },
  { agency: "Weston Police Department", phone: "", location: "" },
  { agency: "Winston Police Department", phone: "", location: "" },
  { agency: "Woodburn Police Department", phone: "", location: "" },
  { agency: "Yamhill Police Department", phone: "", location: "" },
  { agency: "Burns Paiute Tribal Police Department", phone: "", location: "" },
  {
    agency: "Coquille Indian Tribal Police Department",
    phone: "",
    location: "",
  },
  {
    agency: "Columbia River Inter-Tribal Fisheries Enforcement Department",
    phone: "",
    location: "",
  },
  {
    agency:
      "Confederated Tribes of Coos}, Lower Umpqua and Siuslaw Indians Police Department",
    phone: "",
    location: "",
  },
  {
    agency: "Confederated Tribes of Grand Ronde Tribal Police",
    phone: "",
    location: "",
  },
  { agency: "Umatilla Tribal Police Department", phone: "", location: "" },
  { agency: "Warm Springs Tribal Police Department", phone: "", location: "" },
  {
    agency: "Portland Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Portland State University Office of Campus Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Clackamas Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Linn-Benton Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Chemeketa Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Blue Mountain Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Central Oregon Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Clatsop Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Columbia Gorge Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Klamath Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Lane Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Mt. Hood Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Oregon Coast Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  { agency: "University of Oregon Police Department", phone: "", location: "" },
  {
    agency: "Oregon Health and Science University Police",
    phone: "",
    location: "",
  },
  {
    agency: "Southern Oregon University Campus Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Rogue Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Southwestern Oregon Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Tillamook Bay Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Treasure Valley Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  {
    agency: "Umpqua Community College Department of Public Safety",
    phone: "",
    location: "",
  },
  { agency: "Port of Portland Police Department", phone: "", location: "" },
];
