export const Agencies = [
  "Oregon Board of Parole and Post-Prison Supervision",
  "Oregon Department of Corrections",
  "Oregon Department of Justice",
  "Oregon Department of Transportation Motor Carrier Enforcement",
  "Oregon Liquor Control Commission",
  "Oregon State Police",
  "Oregon State Fire Marshal",
  "Oregon Youth Authority",
  "Baker County Sheriff's Office",
  "Benton County Sheriff's Office",
  "Clackamas County Sheriff's Office ",
  "Clatsop County Sheriff's Office",
  "Columbia County Sheriff's Office",
  "Coos County Sheriff's Office",
  "Crook County Sheriff's Office",
  "Curry County Sheriff's Office",
  "Deschutes County Sheriff's Office",
  "Douglas County Sheriff's Office",
  "Gilliam County Sheriff's Office",
  "Grant County Sheriff's Office",
  "Harney County Sheriff's Office",
  "Hood River County Sheriff's Office",
  "Jackson County Sheriff's Office",
  "Jefferson County Sheriff's Office",
  "Josephine County Sheriff's Office",
  "Klamath County Sheriff's Office",
  "Lake County Sheriff's Office",
  "Lane County Sheriff's Office",
  "Lincoln County Sheriff's Office",
  "Linn County Sheriff's Office",
  "Malheur County Sheriff's Office",
  "Marion County Sheriff's Office",
  "Morrow County Sheriff's Office",
  "Multnomah County Sheriff's Office",
  "Polk County Sheriff's Office",
  "Sherman County Sheriff's Office",
  "Tillamook County Sheriff's Office",
  "Umatilla County Sheriff's Office",
  "Union County Sheriff's Office",
  "Wallowa County Sheriff's Office",
  "Wasco County Sheriff's Office",
  "Washington County Sheriff's Office",
  "Wheeler County Sheriff's Office",
  "Yamhill County Sheriff's Office",
  "Adair Village Police Department",
  "Albany Police Department",
  "Amity Police Department",
  "Ashland Police Department",
  "Astoria Police Department",
  "Athena Police Department",
  "Aumsville Police Department",
  "Baker City Police Department",
  "Bandon Police Department",
  "Beaverton Police Department",
  "Bend Police Department",
  "Black Butte Ranch Police Department",
  "Boardman Police Department",
  "Brookings Police Department",
  "Burns Police Department",
  "Butte Falls Police Department",
  "Canby Police Department",
  "Cannon Beach Police Department",
  "Carlton Police Department",
  "Central Point Police Department",
  "Clatskanie Police Department",
  "Coburg Police Department",
  "Columbia City Police Department",
  "Condon Police Department",
  "Coos Bay Police Department",
  "Coquille Police Department",
  "Cornelius Police Department",
  "Corvallis Police Department",
  "Cottage Grove Police Department",
  "Dallas Police Department (Oregon)",
  "Eagle Point Police Department",
  "Enterprise Police Department",
  "Eugene Police Department",
  "Fairview Police Department",
  "Florence Police Department",
  "Forest Grove Police Department",
  "Gearhart Police Department",
  "Gervais Police Department",
  "Gladstone Police Department",
  "Gold Beach Police Department",
  "Grants Pass Department of Public Safety",
  "Gresham Police Department",
  "Hermiston Police Department",
  "Hillsboro Police Department",
  "Hines Police Department",
  "Hood River Police Department",
  "Hubbard Police Department",
  "Independence Police Department",
  "Jacksonville Police Department",
  "John Day Police Department",
  "Junction City Police Department",
  "Keizer Police Department",
  "King City Police Department",
  "Klamath Falls Police Department",
  "La Grande Police Department",
  "Lake Oswego Police Department",
  "Lakeview Police Department",
  "Lebanon Police Department",
  "Lincoln City Police Department",
  "Madras Police Department",
  "Malin Police Department",
  "Manzanita Police Department",
  "McMinnville Police Department",
  "Medford Police Department",
  "Merrill Police Department",
  "Milton-Freewater Police Department",
  "Milwaukie Police Department ",
  "Molalla Police Department",
  "Monmouth Police Department",
  "Mt. Angel Police Department",
  "Myrtle Creek Police Department",
  "Myrtle Point Police Department",
  "Newberg-Dundee Police Department",
  "Newport Police Department",
  "North Bend Police Department",
  "North Plains Police Department",
  "Nyssa Police Department",
  "Oakland Police Department",
  "Oakridge Police Department",
  "Ontario Police Department",
  "Oregon City Police Department ",
  "Pendleton Police Department",
  "Philomath Police Department",
  "Phoenix Police Department",
  "Pilot Rock Police Department",
  "Port Orford Police Department",
  "Portland Police Bureau",
  "Powers Police Department",
  "Prairie City Police Department",
  "Prineville Police Department",
  "Rainier Police Department",
  "Redmond Police Department ",
  "Reedsport Police Department",
  "Rockaway Beach Police Department",
  "Rogue River Police Department",
  "Roseburg Police Department",
  "Salem Police Department",
  "Sandy Police Department",
  "Scappoose Police Department",
  "Seaside Police Department ",
  "Sherwood Police Department",
  "Silverton Police Department",
  "Springfield Police Department",
  "St. Helens Police Department",
  "Stanfield Police Department",
  "Stayton Police Department",
  "Sunriver Police Department",
  "Sutherlin Police Department",
  "Sweet Home Police Department",
  "Talent Police Department",
  "The Dalles Police Department",
  "Tigard Police Department ",
  "Tillamook Police Department",
  "Toledo Police Department",
  "Troutdale Police Department",
  "Tualatin Police Department",
  "Turner Police Department",
  "Umatilla Police Department",
  "Vernonia Police Department",
  "Warrenton Police Department",
  "West Linn Police Department",
  "Weston Police Department",
  "Winston Police Department",
  "Woodburn Police Department",
  "Yamhill Police Department",
  "Burns Paiute Tribal Police Department",
  "Coquille Indian Tribal Police Department",
  "Columbia River Inter-Tribal Fisheries Enforcement Department",
  "Confederated Tribes of Coos, Lower Umpqua and Siuslaw Indians Police Department",
  "Confederated Tribes of Grand Ronde Tribal Police",
  "Umatilla Tribal Police Department",
  "Warm Springs Tribal Police Department",
  "Portland Community College Department of Public Safety",
  "Portland State University Office of Campus Safety",
  "Clackamas Community College Department of Public Safety",
  "Linn-Benton Community College Department of Public Safety",
  "Chemeketa Community College Department of Public Safety",
  "Blue Mountain Community College Department of Public Safety",
  "Central Oregon Community College Department of Public Safety",
  "Clatsop Community College Department of Public Safety",
  "Columbia Gorge Community College Department of Public Safety",
  "Klamath Community College Department of Public Safety",
  "Lane Community College Department of Public Safety",
  "Mt. Hood Community College Department of Public Safety",
  "Oregon Coast Community College Department of Public Safety",
  "University of Oregon Police Department",
  "Oregon Health and Science University Police",
  "Southern Oregon University Campus Public Safety",
  "Rogue Community College Department of Public Safety",
  "Southwestern Oregon Community College Department of Public Safety",
  "Tillamook Bay Community College Department of Public Safety",
  "Treasure Valley Community College Department of Public Safety",
  "Umpqua Community College Department of Public Safety",
  "Port of Portland Police Department",
  "Portland Transit Police",
];
